web-animations/web-animations-next

src/player.js
src/web-animations-next-player.js
test/js/group-player.js
test/js/player.js

Fixes issue https://github.com/web-animations/web-animations-next/issues/268

Implemented a playbackRate setter for the animation group players

---

src/group-constructors.js
test/js/group-player.js

This addresses https://github.com/web-animations/web-animations-next/issues/267

Don't tick a group if its player is in the pending state.

---

src/group-constructors.js
test/js/group-player.js

Reverts web-animations/web-animations-next#272
Test was wrong :(

Revert "Don't tick a group if its player is in the pending state."

---

History.md

1.0.7 Release Notes

---

src/web-animations-next-player.js

Fixes https://github.com/web-animations/web-animations-js/issues/26

Arrange children based on parent timing

---

README.md

Add code tags to Native Fallback section

---

src/deprecation.js
src/keyframe-effect-constructor.js
src/timeline.js
src/web-animations-next-animation.js

API change grace periods + KE.getFrames + fix for shared.deprecated.

---

README.md

Replaces https://github.com/web-animations/web-animations-next/pull/313
@shans @dstockwell ptal

Fix up naming in the readme + small readme changes

---

History.md

Release notes for 2.0.0

---

src/group-constructors.js
test/js/group-constructors.js

First and last child getters

---

src/property-interpolation.js
test/js/color-handler.js

Initial values for most properties

---

src/group-constructors.js
test/js/group-animation.js

Will fix https://github.com/web-animations/web-animations-next/issues/341

Group constructor should reparent

---

src/tick.js

One thing I don't like  about this: performance.now() doesn't seem aligned that well with rAF. So this probably makes one of the frame intervals < 16ms. Probably not noticeable though.

Catch up when gCS is called after long idle period

---

src/group-constructors.js
src/keyframe-effect-constructor.js

Addresses https://github.com/web-animations/web-animations-next/issues/385

Expose AnimationEffect.parent

---

src/timeline.js
src/web-animations-next-animation.js
test/js/web-animations-next-animation.js

Addresses https://github.com/web-animations/web-animations-next/issues/383

Expose animation timeline

---

README.md

Makes `README.md` a bit prettier.

Use language tags for syntax highlighting

---

README.md

Resolves [#43](https://github.com/web-animations/web-animations-js/issues/43).

Add support levels

---

src/matrix-decomposition.js
test/js/matrix-interpolation.js

Spec:
https://drafts.csswg.org/css-values-3/#angles
Issue reported in bug #176 and bug #355

Matrix decomposition: support angle units grad and turn

---

History.md
package.json
src/effect.js
src/normalize-keyframes.js
src/timing-utilities.js
test/js/animation-node.js
test/js/effect.js

Tested locally this that no longer triggers the exception or the warning in Chrome Canary when using groups.

Cherry pick easing TypeError fix onto v1.0.7

---

History.md
package.json
src/keyframe-interpolations.js
src/normalize-keyframes.js
src/timing-utilities.js
test/js/keyframes.js
test/js/timing-utilities.js

Tested locally this that no longer triggers the exception or the warning in Chrome Canary when using groups.

Cherry pick easing TypeError fix onto v2.0.0

---

History.md
package.json
src/keyframe-interpolations.js
src/normalize-keyframes.js
src/timing-utilities.js
test/js/keyframes.js
test/js/timing-utilities.js

Tested locally this that no longer triggers the exception or the warning in Chrome Canary when using groups.

Cherry pick easing TypeError fix onto v2.1.4

---

target-config.js
test/js/visibility-handler.js

Unit test for visibility interpolation.

Test visibility-handler

---

Gruntfile.js
package.json
test/karma-config.js

This task enbles running the Karma Firefox instance in an interactive mode for debugging.

Create debug task for grunt

---

src/keyframe-effect.js

This closes https://github.com/web-animations/web-animations-js/issues/34.

Remove unused _isCurrent function

---

package.json

Fixes https://github.com/web-animations/web-animations-js/issues/78 and https://github.com/web-animations/web-animations-js/issues/79.

Include source files in npm package so the map files actually map onto something
