web-animations/web-animations-next

src/animation-constructor.js
test/js/group-player.js

Don't update a group's children if the group is cancelled (idle play state). This fixed a bug where if you play a group and immediately cancel it, the group continues to play.

Don't update children of cancelled group

---

src/effect-callback.js
src/tick.js
test/js/group-player.js
test/js/tick.js

This fixes a bug where a group who has fill none, and whose children also have fill none, doesn't cancel its effects when it finishes.

Only clear pending effects once they have been applied

---

src/effect-callback.js

`player.finished` and `player.paused` no longer exist.
Manually verified that the `tick()` function in `effect-callback.js` is no longer called after the effect callback has finished.

Fix condition testing when effect callbacks are still ticking

---

src/web-animations-next-player.js

This works around https://github.com/web-animations/web-animations-next/issues/278 which causes https://github.com/Polymer/paper-dropdown-menu/issues/45.
@morethanreal, @dstockwell, @mikelawther

Work around broken fill-forwards cancel in M40

---

src/effect-callback.js
test/js/effect-callback.js

Fixes a bug where custom effects in a sequence were sampling on the first tick of the sequence because null != undefined.

Intial custom effect "last" time fraction should be null, not undef.

---

src/timing-utilities.js
test/js/timing-utilities.js

When 0 or 1 is passed, cubic timing function should return 0 or 1 respectively.
Fixes #311

Return early for special cubic params

---

src/web-animations-next-animation.js
test/js/group-animation.js

Make groups with infinite iteration children work for native-backed polyfill.
Add tests for groups with infinite iteration children.
NB: Tests don't test the bug that this patch fixes, as it only shows with native Animations. However this case used to be a lot worse, so it seems worthwhile having tests.
@dstockwell @shans

Fix groups with infinite iteration children

---

src/timing-utilities.js

Addresses https://github.com/web-animations/web-animations-next/issues/390
Change back to manually defining timing getters and setters. I don't know why this works but it does.

Fix group onfinish bug

---

package.json

This makes Web Animations public on NPM (Node Package Manager), and defines a specific version (this is, unfortunately, required for NPM, and will need to be updated on every release).
Alternative approach: we could leave `version` out (since `web-animations-next` has no notion of versions), and set it only as part of the merge to `web-animations-js`.

Update package.json for NPM 2.1.3

---

src/tick.js

This comes from this issue - https://github.com/web-animations/web-animations-js/issues/35
Thanks & sorry for the delay!

Workaround for window.performance not being available on mobile safari

---

src/web-animations-next-animation.js
test/js/animation-finish-event.js

The definition of onfinish in web-animations-next-animation.js refers
to this.onfinish, where it should be this._onfinish.

Typo fix: Replace onfinish with _onfinish

---

src/animation.js
src/tick.js
test/js/animation.js
test/js/group-animation.js

Safari and Firefox do not consistently call RAF callbacks before
putting up a frame.
* Animation._finishedFlag no longer reflects the finished state of the
animation, instead it indicates whether the finished event is no
longer pending while we are in finished or idle play state.
* getComputedStyle() no longer forces a timing tick and does not
force animations to get a start time, tests have been updated to
stop depending on the old behaviour.
Fixes https://github.com/web-animations/web-animations-next/issues/406

Update and apply effects immediately

---

Gruntfile.js

With the addition of webAnimations1BonusSrc files, it is useful for the
web-animations target to load the polyfill scopeSrc and sharedSrc files
whether or not a native web animations implementation exists. This
patch moves the scopeSrc and sharedSrc files outside of the
webAnimations1Src guard, as is done in the web-animations-next target.
This allows the build* functions in Gruntfile.js to be simplified and
merged.

Always load scope/shared without guard.

---

src/normalize-keyframes.js
src/web-animations-bonus-object-form-keyframes.js
target-config.js
test/js/keyframes.js
web-animations-next-lite.dev.html
web-animations-next.dev.html
web-animations.dev.html

This patch extends the web-animations and web-animations-next
polyfills to accept the object-form syntax for specifying keyframes
(http://w3c.github.io/web-animations/#processing-a-frames-argument).
The capacity is added to the base polyfill, so loading the
web-animations polyfill will enable the new syntax.
It is possible that a browser has a native Web Animations
implementation (and hence does not load the base polyfill), but does
not natively accept object-form keyframes. To address this, this
patch also adds a file to the 'bonus' sources, so the object-form
keyframe syntax can be loaded independently of the base polyfill.

Implement object-form keyframe syntax.

---

src/animation.js
src/element-animatable.js
src/group-constructors.js
src/keyframe-effect-constructor.js
src/keyframe-effect.js
src/web-animations-bonus-cancel-events.js
src/web-animations-bonus-object-form-keyframes.js
src/web-animations-next-animation.js
test/js/animation.js

Following https://codereview.chromium.org/1695633002 and the spec
http://w3c.github.io/web-animations/#dom-animation-id, this patch
implements an optional id field in the Animation object. This field
may be populated via the options argument to Element.animate
(previously called the timingInput argument) and is passed to the
Animation object via a new KeyframeEffect._id field.

Implement Animation.id

---

src/timing-utilities.js
test/js/timing-utilities.js

By reserialising easing input via the native browser's CSS parser we can handle arbitrary capitalisations and escaped characters correctly.
We can rely on escaped characters being serialised consistently according to the serialisation spec:
https://www.w3.org/TR/cssom-1/#serialize-an-identifier

Clean up easings before parsing

---

src/property-interpolation.js
test/js/color-handler.js
test/js/property-interpolation.js

Property names should be specified using camelCase, for example
backgroundColor instead of background-color.

Use of hyphens in property names is deprecated

---

src/keyframe-interpolations.js
src/normalize-keyframes.js
src/timing-utilities.js
test/js/keyframes.js
test/js/timing-utilities.js

There are places in the code where we use AnimationEffectTiming as input to KeyframeEffect, it should conform to the specified interface where easing is a string.
http://w3c.github.io/web-animations/#the-animationeffecttiming-interface
This change is a pre-fix for when toTimingFunction() will throw a TypeError on invalid easing input and break most of our group tests.

Don't store Javascript functions on AnimationEffectTiming.easing or keyframe.easing

---

src/timing-utilities.js
test/js/timing-utilities.js

The polyfill evaluation of cubic Bezier timing functions
gives slightly different results than the native Blink
implementation.
In my testing, this change reduced the absolute error by 63%
while only increasing the number of cubic function evaluations
by 31%
This closes #139

Increase Bezier timing function accuracy

---

src/web-animations-bonus-object-form-keyframes.js

The object-form-keyframes source file uses a call to Element.animate
to decide whether to load the polyfill for the object-form syntax.
If the native browser code supports Element.animate without full
support for object-form syntax, this test can throw a TypeError (see
https://github.com/web-animations/web-animations-js/issues/72). In
this case, the polyfill should proceed to load the polyfill. This
patch implements this behaviour with a try-catch guard around the
Element.animate loading check.

Add try-catch guard to object-form loading check

---

src/deprecation.js
src/timing-utilities.js

Deprecation is a temporary communication signal to users of the polyfill rather than a hard exception that halts JS execution.

Deprecate invalid timing inputs instead of throwing TypeErrors immediately

---

History.md

This was left out from web-animations-next in the 2.2.0 release.

Add missing 2.2.0 version history

---

History.md
package.json

Whoops we didn't increment package.json on web-animations-next for 2.2.0.

Bump version to 2.2.1

---

.gitignore

test.html is a handy file to have around for testing the polyfill manually but shouldn't be checked into the repository. This change saves having to worry about it when doing a `git add -A`.

.gitignore test.html

---

src/web-animations-bonus-object-form-keyframes.js

The catch statement was missing from https://github.com/web-animations/web-animations-next/pull/434, this change adds it so that errors indicate no support instead of propagating out of the polyfill.
Verified manually.

Add missing catch block to object form support test

---

test/js/group-animation.js

Regression test to verify that issue #339 no longer occurs.
This closes #339

Test that cancelling animation clears nested effect

---

src/keyframe-effect-constructor.js
src/timeline.js
src/web-animations-next-animation.js

We now use the internal reference scope.timeline.
Closes #376

Remove references to window.document.timeline

---

package.json

closure-linter-wrapper is a required dependency of the grunt-gjslint plugin package.
npm install on a fresh checkout fails if this dependency isn't made explicit.

Add grunt-gjslint peer dependency

---

package.json

npm install was reporting a warning:
license should be a valid SPDX license expression
Avoid by using Apache-2.0 as specified in http://spdx.org/licenses/

Valid SPDB license expression

---

.travis-setup.sh
.travis.yml

The Travis setup for Firefox Aurora is currently broken because the ppa:ubuntu-mozilla-daily/firefox-aurora repository doesn't have the latest version of Firefox for the version of Linux that Travis uses (Precise).
https://launchpad.net/~ubuntu-mozilla-daily/+archive/ubuntu/firefox-aurora/+packages?field.name_filter=&field.status_filter=published&field.series_filter=precise
The package build fails with `ERROR: Only GCC 4.8 or newer is supported (found version 4.6.3).`.
This change removes the Firefox-aurora option and sets Travis to Firefox-stable so that it is less misleading.

Change Travis config to test on Firefox stable instead of aurora

---

CONTRIBUTING.md
Gruntfile.js
package.json

This change adds a new parameter to `grunt test` and `grunt debug`.
You can now run specific test files e.g. `grunt debug:web-animations-next:test/web-platform-tests/web-animations/animation/pause.html`.
This change also makes `grunt debug` not launch the Firefox browser, instead it just starts the Karma server and provides a URL for you to navigate to.

Add the ability to test a given list of files to `grunt test/debug`

---

test/web-platform-tests-expectations.js

testharness.js uses {}.toString.call(object) to check serialisation of objects. The output `[object Object]` is not something the polyfill can control without monkey patching Object.prototype.toString which would be undesirable for such a minor detail.

Finalise [object Object] serialisation failure expectations

---

test/web-platform-tests-expectations.js

The failures for the polyfill have changed overnight, probably due to a new version of Firefox.
This patch updates the expectations using the `formattedFailures` output from https://github.com/web-animations/web-animations-next/pull/466.

Update web-platform-tests expectations

---

CONTRIBUTING.md
test/karma-testharness-adapter.js
test/web-platform-tests-expectations.js

This change makes the testharness adaptor dump the test failures on the window object for use in `grunt debug`.
It also outputs the failures formatted to be suitable for pasting into expectedFailures in web-platform-tests-expectations.js.
This patch builds upon https://github.com/web-animations/web-animations-next/pull/467.

Dump testharness test failures on window for debug mode

---

.gitmodules
CONTRIBUTING.md
test/karma-testharness-adapter.js
test/web-platform-tests-expectations.js

This change redirects the web-platform-tests submodule to https://github.com/alancutter/web-platform-tests using the nativeShippingAPI branch.
The intention here is to get better coverage of our "web-animations" target by using versions of the tests that restrict themselves to the API surface implemented by the target and supporting native browsers. This will be achieved in future patches.
This change builds upon https://github.com/web-animations/web-animations-next/pull/466.

Use fork of web-platform-tests

---

.gitmodules
CONTRIBUTING.md
Gruntfile.js
package.json
target-config.js
test/karma-config.js
test/karma-testharness-adapter.js
test/resources/testharnessreport.js
test/web-platform-tests-expectations.js

This change enables testing a subset of web-platform-tests/web-animations with the web-animations target.
This change builds upon https://github.com/web-animations/web-animations-next/pull/465.

Test web-animations target with subset of web-platform-tests

---

.gitmodules
CONTRIBUTING.md
Gruntfile.js
package.json
target-config.js
test/karma-config.js
test/karma-testharness-adapter.js
test/resources/testharnessreport.js
test/web-platform-tests-expectations.js

By changing the polyfill.js redirect to being served out of /base/ and including .min.js.map files in the Karma server we can make use of source maps when inspecting minified code.
This change builds upon https://github.com/web-animations/web-animations-next/pull/468.

Enable source maps in Karma

---

src/keyframe-interpolations.js
test/js/keyframes.js
test/web-platform-tests-expectations.js

This patch adds the concept of applyTo and applyFrom to interpolations so that they may affect larger ranges than their start and end offsets. This is useful for the first and last interpolations and mirrors the logic in Blink's KeyframeEffectModelBase::ensureInterpolationEffectPopulated().
This change builds upon https://github.com/web-animations/web-animations-next/pull/469.

Add apply ranges to interpolations

---

src/keyframe-interpolations.js
src/normalize-keyframes.js
src/timing-utilities.js
test/js/keyframes.js
test/js/timing-utilities.js
test/web-platform-tests-expectations.js

Throw TypeErrors for the following scenarios:
- Invalid easing on keyframe.
- Unsorted keyframe offsets as input.
- Out of bounds keyframe offset.
This change builds upon https://github.com/web-animations/web-animations-next/pull/470.

Throw TypeErrors for invalid keyframe inputs

---

src/timing-utilities.js
test/web-platform-tests-expectations.js

An infinite loop in the cubic bezier function in src/timing-utilities.js was
causing us to skip interfaces/KeyframeEffect/effect-easing.html from the
web-platform-tests. This patch changes the loop condition to ensure it exits,
in line with the CubicBezier implementation in Chromium.
In order to achieve the accuracy required by the web-platform-tests
expectations, the epsilon value in the algorithm is also reduced by an order of
magnitude.

Prevent cubic bezier from infinite-looping

---

test/web-platform-tests-expectations.js

After fixing the cubic bezier loop in
https://github.com/web-animations/web-animations-next/pull/476,
it is no longer necessary to skip effect-easing-steps.html from the web platform
tests. This patch removes the skip and instead adds in details of the failing
tests that this reveals.

Update expectations for effect-easing-steps.html

---

src/animation.js
src/web-animations-next-animation.js
test/web-platform-tests-expectations.js

Relevant spec section:
https://w3c.github.io/web-animations/#playing-an-animation-section

Throw InvalidStateError when calling play() on a finished, reversed, infinite duration animation

---

src/animation.js
test/js/animation.js
test/web-platform-tests-expectations.js

This changes our behaviour for pause() on cancelled/idle animations to rewind the current time to the start of the animation.
https://w3c.github.io/web-animations/#pausing-an-animation-section

Make pause() on idle animations set their current time according to playbackRate

---

src/effect-callback.js
src/group-constructors.js
src/keyframe-effect.js
src/timing-utilities.js
src/web-animations-next-animation.js
test/js/group-animation.js
test/js/timing-utilities.js
test/web-platform-tests-expectations.js

Calculating the iteration progress now follows the spec
All stages between active time and iteration progress have been re-written to match the spec. 
https://w3c.github.io/web-animations/#calculating-the-iteration-progress

Simple iteration progress works

---

src/timing-utilities.js
test/web-platform-tests-expectations.js

Now a different set of tests fail... but I think this is a better position to be in.

Allow cubic bezier to accept value outside [0,1]

---

test/resources/testharnessreport.js

Now that Firefox has shipped Element.animate() the polyfill's web-animations-js target is effectively doing nothing during tests.
This change disables access to native's Element.animate() in tests so that the polyfill always provides its own implementation.

Disable native fallback during web-platform-tests

---

test/web-platform-tests-expectations.js

Firefox 48 seems to no longer output "use strict" in its function serialisation.

Update expectations for Firefox 48

---

src/color-handler.js
test/js/color-handler.js

Animation of 'fill', 'flood-color', 'lighting-color', 'stop-color',
'stroke' is now supported.
https://github.com/web-animations/web-animations-js/issues/81

Support animation of SVG color properties
